### ISSUE TITLE
2016.10.31-2016.11.01 breakfast

### ISSUE THREAD

**Issue by matsuo-y** [matsuo-y/git-practice#12]
朝食は、10/31から11/1までの開発期間を想定した練習

今日の朝ごはんを以下のサイトで公開できる

ステージング環境： https://staging-git-practice-breakfast.herokuapp.com/
本番環境：　https://matsuo-y.github.io/git-practice-breakfast/

担当者は以下のとおり(作業内容はREADME.mdに記載)
- issue作成者：土井
- branch作成者：郷野
- 開発担当者(朝食報告、2名)：中村、譚
※月をまたぐため、11/1分はbreakfast/201611.htmlとして新しくファイルを作成する
- 検収担当者：松尾
- リリース担当者：姜

**Comment by matsuo-y** [comment]
@opst-D-Take 
git-practice-breakfast側のissueをクローズしたら、こちらもクローズをお願いします。

**Comment by opst-D-Take** [comment]
リリース完了しましたので、クローズいたします。
