### ISSUE TITLE
2016.11.7-2016.11.8 breakfast

### ISSUE THREAD

**Issue by matsuo-y** [matsuo-y/git-practice#16]
11/7,11/8の朝ごはんを以下のサイトで公開できる

branch作成以降の実際の開発タスクについては、matsuo-y/git-practice-breakfastリポジトリで行う
※matsuo-y/git-practice-breakfastリポジトリにはissueは作成せず、PRは直接このissueにconnectさせること

origin/#{N}-breakfastで作業を行い、origin/stagingにPRしてマージする
コミットメッセージは、`fix` を記載しないようにし、誰の朝食か（どんな修正か）がわかる文言にする
PRのタイトルは、`fix` を記載しないようにし、誰の朝食かがわかる文言にする

作業担当者は、下記の通りとする
- issue作成者：上田
- branch作成者：譚
- 開発担当者(朝食報告、2名)：譚、姜
- 検収担当者：土井
- リリース担当者：根本

ステージング環境： https://staging-git-practice-breakfast.herokuapp.com/breakfast/201611.html
本番環境：　https://matsuo-y.github.io/git-practice-breakfast/breakfast/201611.html

ただし、PR時ににはPR番号{N}の環境でサイトをブラウザで確認する
PR環境：　https://git-practice-breakfast-pr-{N}.herokuapp.com/

issue発行者は、各作業が終わった段階でチェックをつけ、releases/tagsの設定まで終わった段階でこのissueをクローズする
- [x] issue作成
- [x] issue branch作成
- [x] stagingへのPR
- [x] masterへのPR
- [x] masterへのreleases/tags設定

**Comment by jiangheqing** [comment]
@opst-D-Take 

2016.11.07 の朝食を追加しました。レビューをお願い致します。

**Comment by jiangheqing** [comment]
https://github.com/matsuo-y/git-practice-breakfast/pull/22
