### ISSUE TITLE
2016.11.7 conflict lunch

### ISSUE THREAD

**Issue by opst-D-Take** [matsuo-y/git-practice#20]
11/7の昼ごはんを以下のサイトで公開できる

branch作成以降の実際の開発タスクについては、matsuo-y/git-practice-lunchリポジトリで行う
※matsuo-y/git-practice-lunchリポジトリにはissueは作成せず、PRは直接このissueにconnectさせること

origin/#{N}-lunchで作業を行い、origin/stagingにPRしてマージする
コミットメッセージは、`fix` を記載しないようにし、誰の昼食か（どんな修正か）がわかる文言にする
PRのタイトルは、`fix` を記載しないようにし、誰の昼食かがわかる文言にする

作業担当者は、下記の通りとする
- issue作成者：土井
- branch作成者：姜
- 開発担当者(昼食報告、1名)：上田
- 検収担当者：譚
- リリース担当者：中村

ステージング環境： https://staging-git-practice-lunch.herokuapp.com/lunch/201611.html
本番環境：　https://matsuo-y.github.io/git-practice-lunch/lunch/201611.html

ただし、PR時ににはPR番号{N}の環境でサイトをブラウザで確認する
PR環境：　https://git-practice-lunch-pr-{N}.herokuapp.com/

issue発行者は、各作業が終わった段階でチェックをつけ、releases/tagsの設定まで終わった段階でこのissueをクローズする
- [x] issue作成
- [x] issue branch作成
- [x] stagingへのPR
- [x] masterへのPR
- [x] masterへのreleases/tags設定

**Comment by jiangheqing** [comment]
@opst-ueda 

連絡が遅くなりました。　本日の昼ごはんのブランチを作成いたしました。

**Comment by opsttan** [comment]
@opst-D-Take 
stagingへのPRをマージしました。
masterへマージのPRの作成をお願いいたします。

**Comment by opst-D-Take** [comment]
@opstnakamura masterへのPRを作成しましたので、ご確認頂いた後、マージをお願いいたします。

**Comment by ghost** [comment]
- [x] masterへのreleases/tags設定

https://github.com/matsuo-y/git-practice-lunch/releases

が必要ですね。リリース担当者は。

**Comment by opstnakamura** [comment]
タグをつけました。

**Comment by opst-D-Take** [comment]
作業完了しましたのでクローズします。
