### ISSUE TITLE
2016.11.8 lunch

### ISSUE THREAD

**Issue by opst-nemoto** [matsuo-y/git-practice#22]
11/8の昼ごはんを以下のサイトで公開できる

branch作成以降の実際の開発タスクについては、matsuo-y/git-practice-lunchリポジトリで行う
※matsuo-y/git-practice-lunchリポジトリにはissueは作成せず、PRは直接このissueにconnectさせること

origin/#{N}-lunchで作業を行い、origin/stagingにPRしてマージする
コミットメッセージは、`fix` を記載しないようにし、誰の昼食か（どんな修正か）がわかる文言にする
PRのタイトルは、`fix` を記載しないようにし、誰の昼食かがわかる文言にする

作業担当者は、下記の通りとする
- issue作成者：根本
- branch作成者：中村
- 開発担当者(昼食報告、1名)：土井
- 検収担当者：姜
- リリース担当者：上田

ステージング環境： https://staging-git-practice-lunch.herokuapp.com/lunch/201611.html
本番環境：　https://matsuo-y.github.io/git-practice-lunch/lunch/201611.html

ただし、PR時ににはPR番号{N}の環境でサイトをブラウザで確認する
PR環境：　https://git-practice-lunch-pr-{N}.herokuapp.com/

issue発行者は、各作業が終わった段階でチェックをつけ、releases/tagsの設定まで終わった段階でこのissueをクローズする
- [x] issue作成
- [x] issue branch作成
- [x] stagingへのPR
- [x] masterへのPR
- [x] masterへのreleases/tags設定

**Comment by opst-ueda** [comment]
あ、tagを切るのはリリース担当じゃなくて、issue発行者なんですね…間違えた…

@nemoto 
tag切っちゃいました…issueのクローズだけお願いします。

**Comment by opst-nemoto** [comment]
releases/tagsの設定まで完了したのでクローズします。

**Comment by ghost** [comment]
release/tag を付与したことおよびそのURLを記載してから、issueを close しましょ

**Comment by opst-nemoto** [comment]
release/tagのURLは以下となります。
https://github.com/matsuo-y/git-practice-lunch/releases/tag/v1.4
