### ISSUE TITLE
2016.11.9 根本さんの昼食

### ISSUE THREAD

**Issue by matsuo-y** [matsuo-y/git-practice#26]
11/9の根本さんの昼ごはんを以下のサイトで公開できる

branch作成以降の実際の開発タスクについては、matsuo-y/git-practice-lunchリポジトリで行う
※matsuo-y/git-practice-lunchリポジトリにはissueは作成せず、PRは直接このissueにconnectさせること

origin/git-practice/#{N}-{作業者名}で作業を行い、origin/stagingにPRしてマージする
コミットメッセージは、`fix` を記載しないようにし、誰の昼食か（どんな修正か）がわかる文言にする
PRのタイトルは、`fix` を記載しないようにし、誰の昼食かがわかる文言にする

branch作成からリリース作業(releases/tags設定)までは全て開発担当者が行う
PRのレビューはレビュー担当者にアサインする
- 開発担当者：根本
- レビュー担当者：郷野

ステージング環境： https://staging-git-practice-lunch.herokuapp.com/lunch/201611.html
本番環境：　https://matsuo-y.github.io/git-practice-lunch/lunch/201611.html

ただし、PR時ににはPR番号{N}の環境でサイトをブラウザで確認する
PR環境：　https://git-practice-lunch-pr-{N}.herokuapp.com/

issue作成者は、各作業が終わった段階でチェックをつけ、releases/tagsの設定まで終わった段階でこのissueをクローズする
- [x] stagingへのPRマージ
- [x] masterへのPRマージ
- [x] masterへのreleases/tags設定

**Comment by matsuo-y** [comment]
@opst-nemoto 
設定したreleases/tagsの画面のURLをこちらに記載をお願いします。

**Comment by opst-nemoto** [comment]
@matsuo.y releases/tagsの設定が完了しました。再度ご確認お願いします。
https://github.com/matsuo-y/git-practice-lunch/releases/tag/v1.6

**Comment by matsuo-y** [comment]
確認できました、ありがとうございます。
releases/tagsの設定まで完了しましたので、クローズします。
