### ISSUE TITLE
2017.01.30 lunch

### ISSUE THREAD

**Issue by gonomk** [matsuo-y/git-practice#28]
1/30の昼ごはんを以下のサイトで公開できる

branch作成以降の実際の開発タスクについては、matsuo-y/git-practice-lunchリポジトリで行う
※matsuo-y/git-practice-lunchリポジトリにはissueは作成せず、PRは直接このissueにconnectさせること

origin/#{N}-lunchで作業を行い、origin/stagingにPRしてマージする
コミットメッセージは、`fix` を記載しないようにし、誰の昼食か（どんな修正か）がわかる文言にする
PRのタイトルは、`fix` を記載しないようにし、誰の昼食かがわかる文言にする

作業担当者は、下記の通りとする
- issue作成者：郷野
- branch作成者：姜
- 開発担当者(昼食報告、1名)：姜
- 検収担当者：橋本
- リリース担当者：橋本

ステージング環境： https://staging-git-practice-lunch.herokuapp.com/lunch/201701.html
本番環境：　https://matsuo-y.github.io/git-practice-lunch/lunch/201701.html

ただし、PR時ににはPR番号{N}の環境でサイトをブラウザで確認する
PR環境：　https://git-practice-lunch-pr-{N}.herokuapp.com/

issue発行者は、各作業が終わった段階でチェックをつけ、releases/tagsの設定まで終わった段階でこのissueをクローズする
- [x] issueを作成
- [x] issue branchを作成
- [x] staging branchへのPRを作成しマージ完了
- [x] master branchへのPRを作成しマージ完了
- [x] master branchのHEADにreleases/tags設定

**Comment by opst-hashimoto** [comment]
完了しました。
https://github.com/matsuo-y/git-practice-lunch/releases/tag/v1.8
