### ISSUE TITLE
2017.02.06 橋本さんlunch

### ISSUE THREAD

**Issue by ghost** [matsuo-y/git-practice#37]
## 作業内容
2/6の橋本さんの昼ごはんを以下のサイトで公開できる

branch作成以降の実際の開発タスクについては、matsuo-y/git-practice-lunchリポジトリで行う
※matsuo-y/git-practice-lunchリポジトリにはissueは作成せず、PRは直接このissueにconnectさせること

origin/#{N}-lunchで作業を行い、origin/stagingにPRしてマージする
コミットメッセージは、`fix` を記載しないようにし、誰の昼食か（どんな修正か）がわかる文言にする
PRのタイトルは、`fix` を記載しないようにし、誰の昼食かがわかる文言にする

## 開発時に使用する環境
環境 | URL
--- | ---
PR環境 | https://git-practice-lunch-pr-{N}.herokuapp.com/
ステージング環境 | https://staging-git-practice-lunch.herokuapp.com/lunch/201702.html
本番環境 | https://matsuo-y.github.io/git-practice-lunch/lunch/201702.html

  PR時にはPR番号{N}の環境をブラウザで確認する

## 作業担当者の割り当て
- issue作成者：藤本
- branch作成者：橋本
- 開発担当者(昼食報告、1名)：橋本
- 検収担当者：姜
- リリース担当者：姜

## 判定基準
- [x] issue作成者が、issueを作成した
- [x] branch作成者が、issue branchを作成した
- [x] 開発担当者が、staging branchへのPRを作成した
- [x] 検収担当者が、staging branchへのPRをマージ完了した
- [x] リリース担当者が、master branchへのPRを作成した
- [x] リリース担当者が、master branchのHEADに対して、releases/tagsを設定し、PRに記載した
- [x] リリース担当者が、master branchへのPRをマージ完了した
- [x] リリース担当者が、master branch がデプロイされた結果を確認し、issueに確認した結果を記載した
- [x] リリース担当者が、issueをcloseした

**Comment by opst-hashimoto** [comment]
本ISSUEのリリースを完了いたしました。
https://github.com/matsuo-y/git-practice-lunch/releases/tag/v2.4

**Comment by jiangheqing** [comment]
@opst-hashimoto 

ありがとうございます。

**Comment by ghost** [comment]
>  リリース担当者が、master branch がデプロイされた結果を確認し、issueに確認した結果を記載した

確認した結果はどこ？

**Comment by jiangheqing** [comment]
@opst-fujimoto 

>リリース担当者が、master branch がデプロイされた結果を確認し、issueに確認した結果を記載した
>確認した結果はどこ？

⇒　確認した結果とは、下記のようなもので問題ないのでしょうか。

本日（2/6）のランチが下記URL（本番環境）にデプロイされたことを確認した。
https://matsuo-y.github.io/git-practice-lunch/lunch/201702.html

**Comment by ghost** [comment]
https://lgtm.in/i/o0GVVzPcq

Data URLはだめだな。。。 slackで画像を流してくれない

**Comment by ghost** [comment]
http://i.imgur.com/8xuL4Wm.gif

**Comment by jiangheqing** [comment]
![default](https://cloud.githubusercontent.com/assets/22759025/22642281/7258b094-ec9d-11e6-97f6-b8f4422cc470.gif)

**Comment by jiangheqing** [comment]
リリース完了いたしました。
![yes](https://cloud.githubusercontent.com/assets/22759025/22642406/e3f06698-ec9d-11e6-9045-8f88b5e2d139.gif)
