### ISSUE TITLE
2017.3.22-2017.3.23 breakfast

### ISSUE THREAD

**Issue by opst-nemoto** [matsuo-y/git-practice#44]
## 作業内容
3/22、3/23のの朝ごはんを以下のサイトで公開できる

branch作成以降の実際の開発タスクについては、matsuo-y/git-practice-breakfastリポジトリで行う
※matsuo-y/git-practice-breakfastリポジトリにはissueは作成せず、PRは直接このissueにconnectさせること

origin/git-practice/#{N}-breakfastで作業を行い、origin/stagingにPRしてマージする
また開発担当者はorigin/git-practice/#{N}-breakfastとは別のブランチを作成して作業を実施する
コミットメッセージは、`fix` を記載しないようにし、誰の昼食か（どんな修正か）がわかる文言にする
PRのタイトルは、`fix` を記載しないようにし、誰の昼食かがわかる文言にする

## 開発時に使用する環境
環境 | URL
--- | ---
PR環境 | https://git-practice-breakfast-pr-{N}.herokuapp.com/
ステージング環境 | https://staging-git-practice-breakfast.herokuapp.com/breakfast/201703.html
本番環境 | https://matsuo-y.github.io/git-practice-breakfast/breakfast/201703.html

  PR時にはPR番号{N}の環境をブラウザで確認する

## 作業担当者の割り当て
- issue作成者：根本
- branch作成者：大島
- 開発担当者(昼食報告、1名)：根本、大島
- 検収担当者：根本
- リリース担当者：大島

## 判定基準
- [x] issue作成者が、issueを作成した
- [x] branch作成者が、issue branchを作成した
- [x] 開発担当者が、staging branchへのPRを作成した
- [x] 検収担当者が、staging branchへのPRをマージ完了した
- [x] リリース担当者が、master branchへのPRを作成した
- [x] 検収担当者が、master branchへのPRをマージ完了した
- [x] リリース担当者が、master branchのHEADに対して、releases/tagsを設定し、issueに記載した
- [x] リリース担当者が、master branch がデプロイされた結果を確認し、issueに確認した結果を記載した
- [x] 検収担当者が、issueをcloseした

**Comment by opst-oshima** [comment]
リリースタグを設定しました。
https://github.com/matsuo-y/git-practice-breakfast/releases/tag/v1.2

**Comment by opst-oshima** [comment]
本番環境にデプロイされました。
![image](https://cloud.githubusercontent.com/assets/26425322/24241266/93b29372-0ff7-11e7-9645-b88f6e9a5762.png)

**Comment by opst-nemoto** [comment]
本番環境にデプロイが確認できたので、クローズします。
