### ISSUE TITLE
2017.04.03 津村さんlunch

### ISSUE THREAD

**Issue by opsttan** [matsuo-y/git-practice#46]
## 作業内容
4/3の津村さんの昼ごはんを以下のサイトで公開できる

branch作成以降の実際の開発タスクについては、matsuo-y/git-practice-lunchリポジトリで行う
※matsuo-y/git-practice-lunchリポジトリにはissueは作成せず、PRは直接このissueにconnectさせること

origin/#{N}-{name}-lunchで作業を行い、origin/stagingにPRしてマージする
コミットメッセージは、誰の昼食か（どんな修正か）がわかる文言にする
PRのタイトルは、誰の昼食かがわかる文言にする

## 開発時に使用する環境
環境 | URL
--- | ---
PR環境 | https://git-practice-lunch-pr-{N}.herokuapp.com/
ステージング環境 | https://staging-git-practice-lunch.herokuapp.com/lunch/201704.html
本番環境 | https://matsuo-y.github.io/git-practice-lunch/lunch/201704.html

  PR時にはPR番号{N}の環境をブラウザで確認する

## 作業担当者の割り当て
- issue作成者：譚
- branch作成者：津村
- 開発担当者(昼食報告、1名)：津村
- 検収担当者：譚
- リリース担当者：津村

## 判定基準
- [x] issue作成者が、issueを作成した
- [x] branch作成者が、issue branchを作成した
- [x] 開発担当者が、staging branchへのPRを作成した
- [x] 検収担当者が、staging branchへのPRをマージ完了した
- [x] リリース担当者が、master branchへのPRを作成した
- [x] 検収担当者が、master branchへのPRをマージ完了した
- [x] リリース担当者が、master branchのHEADに対して、releases/tagsを設定し、PRに記載した
- [x] リリース担当者が、master branch がデプロイされた結果を確認し、issueに確認した結果を記載した
- [x] 検収担当者が、issueをcloseした

**Comment by acn-tsumura** [comment]
@opsttan staging環境へのPR作成しました、確認をお願いします。
https://github.com/matsuo-y/git-practice-lunch/pull/74

**Comment by opsttan** [comment]
@opst-tsumura 
①アサイン変更されていません。
②ＰＲの番号は正しくありません。
③connectできていません

**Comment by acn-tsumura** [comment]
本番環境にデプロイされたことを確認しました。

![fireshot capture 5 - lunch history 2017 04_ - https___matsuo-y github io_git-prac](https://cloud.githubusercontent.com/assets/12555037/24600839/6f0cd7f6-1891-11e7-9f73-a72d234e1e3c.png)

**Comment by opsttan** [comment]
確認しました。
