### ISSUE TITLE
waffleにReview カラム（レーン）を追加する

### ISSUE THREAD

**Issue by opst-fujimoto** [matsuo-y/git-practice#5]
staging, masterブランチへのPRは、`In Progress` カラムではなく、別のカラムで、Issue/PRの状態を把握したいため、

https://waffle.io/matsuo-y/git-practice/settings/columns

の設定画面にて、In Progressの次に、`Review` カラムを追加する

例：
![image](https://cloud.githubusercontent.com/assets/15703253/19643177/eefa341e-9a23-11e6-9727-c61f9c1f7158.png)

**Comment by matsuo-y** [comment]
設定を行いましたので、ご確認をお願いいたします。
https://waffle.io/matsuo-y/git-practice

![image](https://cloud.githubusercontent.com/assets/8816337/19669653/096f8740-9a9c-11e6-8598-2bcf956c3990.png)

![image](https://cloud.githubusercontent.com/assets/8816337/19669660/1277be20-9a9c-11e6-9f1a-71be94e5490c.png)

**Comment by opst-fujimoto** [comment]
ok
