### ISSUE TITLE
2017.04.05 津村さんlunch

### ISSUE THREAD

**Issue by opst-nemoto** [matsuo-y/git-practice#50]
## 作業内容
4/5の津村さんの昼ごはんを以下のサイトで公開できる

branch作成以降の実際の開発タスクについては、matsuo-y/git-practice-lunchリポジトリで行う
※matsuo-y/git-practice-lunchリポジトリにはissueは作成せず、PRは直接このissueにconnectさせること

origin/#{N}-{name}-lunchで作業を行い、origin/stagingにPRしてマージする
コミットメッセージは、誰の昼食か（どんな修正か）がわかる文言にする
PRのタイトルは、誰の昼食かがわかる文言にする

## 開発時に使用する環境
環境 | URL
--- | ---
PR環境 | https://git-practice-lunch-pr-{N}.herokuapp.com/
ステージング環境 | https://staging-git-practice-lunch.herokuapp.com/lunch/201704.html
本番環境 | https://matsuo-y.github.io/git-practice-lunch/lunch/201704.html

  PR時にはPR番号{N}の環境をブラウザで確認する

## 作業担当者の割り当て
- issue作成者：根本
- branch作成者：津村
- 開発担当者(昼食報告、1名)：津村
- 検収担当者：大島
- リリース担当者：津村

## 判定基準
- [x] issue作成者が、issueを作成した
- [x] branch作成者が、issue branchを作成した
- [x] 開発担当者が、staging branchへのPRを作成した
- [x] 検収担当者が、staging branchへのPRをマージ完了した
- [x] リリース担当者が、master branchへのPRを作成した
- [x] 検収担当者が、master branchへのPRをマージ完了した
- [x] リリース担当者が、master branchのHEADに対して、releases/tagsを設定し、issueに記載した
- [x] リリース担当者が、master branch がデプロイされた結果を確認し、issueに確認した結果を記載した
- [x] 検収担当者が、issueをcloseした

**Comment by acn-tsumura** [comment]
リリースタグを設定しました。

https://github.com/matsuo-y/git-practice-lunch/releases
↓　（修正）
https://github.com/matsuo-y/git-practice-lunch/releases/tag/v3.7

**Comment by acn-tsumura** [comment]
本番環境へのデプロイを確認しましたので、クローズをお願いします。

![issue50_1](https://cloud.githubusercontent.com/assets/12555037/24738784/166ea680-1ad3-11e7-8bfd-f55c91872afb.png)

**Comment by ghost** [comment]
> リリースタグを設定しました。
> https://github.com/matsuo-y/git-practice-lunch/releases

リリースタグへのリンクは、今回のリリースタグを示しているものを使用したほうがよいかと思います。
今回は
`https://github.com/matsuo-y/git-practice-lunch/releases/tag/v3.7`
こちらになるかと思います。

**Comment by acn-tsumura** [comment]
@opst-ezaki 了解です。

**Comment by ghost** [comment]
確認しましたのでクローズします。
