### ISSUE TITLE
2017.04.05 江嵜さんlunch

### ISSUE THREAD

**Issue by opst-nemoto** [matsuo-y/git-practice#51]
## 作業内容
4/5の江嵜さんの昼ごはんを以下のサイトで公開できる

branch作成以降の実際の開発タスクについては、matsuo-y/git-practice-lunchリポジトリで行う
※matsuo-y/git-practice-lunchリポジトリにはissueは作成せず、PRは直接このissueにconnectさせること

origin/#{N}-{name}-lunchで作業を行い、origin/stagingにPRしてマージする
コミットメッセージは、誰の昼食か（どんな修正か）がわかる文言にする
PRのタイトルは、誰の昼食かがわかる文言にする

## 開発時に使用する環境
環境 | URL
--- | ---
PR環境 | https://git-practice-lunch-pr-{N}.herokuapp.com/
ステージング環境 | https://staging-git-practice-lunch.herokuapp.com/lunch/201704.html
本番環境 | https://matsuo-y.github.io/git-practice-lunch/lunch/201704.html

  PR時にはPR番号{N}の環境をブラウザで確認する

## 作業担当者の割り当て
- issue作成者：根本
- branch作成者：江嵜
- 開発担当者(昼食報告、1名)：江嵜
- 検収担当者：津村
- リリース担当者：江嵜

## 判定基準
- [x] issue作成者が、issueを作成した
- [x] branch作成者が、issue branchを作成した
- [x] 開発担当者が、staging branchへのPRを作成した
- [x] 検収担当者が、staging branchへのPRをマージ完了した
- [x] リリース担当者が、master branchへのPRを作成した
- [x] 検収担当者が、master branchへのPRをマージ完了した
- [x] リリース担当者が、master branchのHEADに対して、releases/tagsを設定し、issueに記載した
- [x] リリース担当者が、master branch がデプロイされた結果を確認し、issueに確認した結果を記載した
- [x] 検収担当者が、issueをcloseした

**Comment by ghost** [comment]
リリースタグの設定をしました。
https://github.com/matsuo-y/git-practice-lunch/releases/tag/v3.5

**Comment by ghost** [comment]
本番環境へデプロイされました。
![image](https://cloud.githubusercontent.com/assets/26862113/24691609/75e8d154-1a0f-11e7-890f-6c0260cbd462.png)

**Comment by ghost** [comment]
@opst-tsumura masterへのデプロイを行い、デプロイ結果を掲載しました。
ご確認お願いいたします。

**Comment by acn-tsumura** [comment]
確認しました。クローズします。
