### ISSUE TITLE
2017.04.05 大島さんlunch

### ISSUE THREAD

**Issue by opst-nemoto** [matsuo-y/git-practice#52]
## 作業内容
4/5の大島さんの昼ごはんを以下のサイトで公開できる

branch作成以降の実際の開発タスクについては、matsuo-y/git-practice-lunchリポジトリで行う
※matsuo-y/git-practice-lunchリポジトリにはissueは作成せず、PRは直接このissueにconnectさせること

origin/#{N}-{name}-lunchで作業を行い、origin/stagingにPRしてマージする
コミットメッセージは、誰の昼食か（どんな修正か）がわかる文言にする
PRのタイトルは、誰の昼食かがわかる文言にする

## 開発時に使用する環境
環境 | URL
--- | ---
PR環境 | https://git-practice-lunch-pr-{N}.herokuapp.com/
ステージング環境 | https://staging-git-practice-lunch.herokuapp.com/lunch/201704.html
本番環境 | https://matsuo-y.github.io/git-practice-lunch/lunch/201704.html

  PR時にはPR番号{N}の環境をブラウザで確認する

## 作業担当者の割り当て
- issue作成者：根本
- branch作成者：大島
- 開発担当者(昼食報告、1名)：大島
- 検収担当者：江嵜
- リリース担当者：大島

## 判定基準
- [x] issue作成者が、issueを作成した
- [x] branch作成者が、issue branchを作成した
- [x] 開発担当者が、staging branchへのPRを作成した
- [x] 検収担当者が、staging branchへのPRをマージ完了した
- [x] リリース担当者が、master branchへのPRを作成した
- [x] 検収担当者が、master branchへのPRをマージ完了した
- [x] リリース担当者が、master branchのHEADに対して、releases/tagsを設定し、issueに記載した
- [x] リリース担当者が、master branch がデプロイされた結果を確認し、issueに確認した結果を記載した
- [x] 検収担当者が、issueをcloseした

**Comment by opst-oshima** [comment]
リリースタグを設定しました。
https://github.com/matsuo-y/git-practice-lunch/releases/tag/v3.6

**Comment by opst-oshima** [comment]
本番環境にデプロイされました。
![image](https://cloud.githubusercontent.com/assets/26425322/24697019/8fc06008-1a26-11e7-8a2e-a1caa6460306.png)

**Comment by opst-oshima** [comment]
@opst-ezaki デプロイ結果を掲載しました。ご確認お願いします。

**Comment by ghost** [comment]
確認しました。クローズします。
