### ISSUE TITLE
2016.10.26-27 breakfast

### ISSUE THREAD

**Issue by opst-fujimoto** [matsuo-y/git-practice#6]
朝食は、10/26から27までの開発期間を想定した練習

今日の朝ごはんを以下のサイトで公開できる

ステージング環境： https://staging-git-practice-breakfast.herokuapp.com/breakfast/201610.html
本番環境：　https://matsuo-y.github.io/git-practice-breakfast/breakfast/201610.html

担当者は以下のとおり(作業内容はREADME.mdに記載)
# 朝食(matsuo-y/git-practice-breakfast#7)
- issue作成者：松尾
- branch作成者：譚
- PR担当者(朝食報告担当)：姜、土井
- リリース担当者：郷野

**Comment by matsuo-y** [comment]
masterへリリースしたためクローズします。
