### ISSUE TITLE
2017.04.10 江嵜さんlunch

### ISSUE THREAD

**Issue by gonomk** [matsuo-y/git-practice#60]
## 作業内容
4/10の江嵜さんの昼ごはんを以下のサイトで公開できる

branch作成以降の実際の開発タスクについては、matsuo-y/git-practice-lunchリポジトリで行う
※matsuo-y/git-practice-lunchリポジトリにはissueは作成せず、PRは直接このissueにconnectさせること

origin/#{N}-{name}-lunchで作業を行い、origin/stagingにPRしてマージする
コミットメッセージは、誰の昼食か（どんな修正か）がわかる文言にする
PRのタイトルは、誰の昼食かがわかる文言にする

## 開発時に使用する環境
環境 | URL
--- | ---
PR環境 | https://git-practice-lunch-pr-{N}.herokuapp.com/
ステージング環境 | https://staging-git-practice-lunch.herokuapp.com/lunch/201704.html
本番環境 | https://matsuo-y.github.io/git-practice-lunch/lunch/201704.html

  PR時にはPR番号{N}の環境をブラウザで確認する

## 作業担当者の割り当て
- issue作成者：郷野
- branch作成者：江嵜
- 開発担当者(昼食報告、1名)：江嵜
- 検収担当者：津村
- リリース担当者：江嵜

## 判定基準
- [x] issue作成者が、issueを作成した
- [x] branch作成者が、issue branchを作成した
- [x] 開発担当者が、staging branchへのPRを作成した
- [x] 検収担当者が、staging branchへのPRをマージ完了した
- [x] リリース担当者が、master branchへのPRを作成した
- [x] 検収担当者が、master branchへのPRをマージ完了した
- [x] リリース担当者が、master branchのHEADに対して、releases/tagsを設定し、issueに記載した
- [x] リリース担当者が、master branch がデプロイされた結果を確認し、issueに確認した結果を記載した
- [x] 検収担当者が、issueをcloseした

**Comment by ghost** [comment]
タグを設定してリリースを行いました。
https://github.com/matsuo-y/git-practice-lunch/releases/tag/v4.2

**Comment by ghost** [comment]
デプロイされたことを確認できました。
![image](https://cloud.githubusercontent.com/assets/26862113/24851671/880e3186-1e0f-11e7-8e14-5a77e184a12b.png)

**Comment by ghost** [comment]
本過程において staging からブランチを切った後、
マージまでに差分が発生しなかったため、
コンフリクトは発生しませんでした。

**Comment by ghost** [comment]
@opst-tsumura 
リリースタグを設定し、デプロイを確認しました。
ご確認お願いいたします。

**Comment by acn-tsumura** [comment]
@opst-ezaki 確認しました。クローズします。
