### ISSUE TITLE
2017.04.10 津村さんlunch

### ISSUE THREAD

**Issue by gonomk** [matsuo-y/git-practice#61]
## 作業内容
4/10の津村さんの昼ごはんを以下のサイトで公開できる

branch作成以降の実際の開発タスクについては、matsuo-y/git-practice-lunchリポジトリで行う
※matsuo-y/git-practice-lunchリポジトリにはissueは作成せず、PRは直接このissueにconnectさせること

origin/#{N}-{name}-lunchで作業を行い、origin/stagingにPRしてマージする
コミットメッセージは、誰の昼食か（どんな修正か）がわかる文言にする
PRのタイトルは、誰の昼食かがわかる文言にする

## 開発時に使用する環境
環境 | URL
--- | ---
PR環境 | https://git-practice-lunch-pr-{N}.herokuapp.com/
ステージング環境 | https://staging-git-practice-lunch.herokuapp.com/lunch/201704.html
本番環境 | https://matsuo-y.github.io/git-practice-lunch/lunch/201704.html

  PR時にはPR番号{N}の環境をブラウザで確認する

## 作業担当者の割り当て
- issue作成者：郷野
- branch作成者：津村
- 開発担当者(昼食報告、1名)：津村
- 検収担当者：大島
- リリース担当者：津村

## 判定基準
- [x] issue作成者が、issueを作成した
- [x] branch作成者が、issue branchを作成した
- [x] 開発担当者が、staging branchへのPRを作成した
- [x] 検収担当者が、staging branchへのPRをマージ完了した
- [x] リリース担当者が、master branchへのPRを作成した
- [x] 検収担当者が、master branchへのPRをマージ完了した
- [x] リリース担当者が、master branchのHEADに対して、releases/tagsを設定し、issueに記載した
- [x] リリース担当者が、master branch がデプロイされた結果を確認し、issueに確認した結果を記載した
- [x] 検収担当者が、issueをcloseした

**Comment by acn-tsumura** [comment]
下記PRにてConfilct発生。解消します。
https://github.com/matsuo-y/git-practice-lunch/pull/104

作業記録
１．#61-tsumura-lunchにstagingをマージ

**Comment by acn-tsumura** [comment]
マージ対象コミット：231dfb2c344baef3875369d282f914f4f66ecbbe 
マージ先：#61-tsumura-lunch

**Comment by acn-tsumura** [comment]
２．コンフリクトしたファイルをエディタで修正
３．SourceTree上で「解決済」とマーク
４．コミット：5e5974ee4b1f5bdafc86721d975c93a48bfdad07

**Comment by acn-tsumura** [comment]
５．PR上のスクリーンショットを修正

**Comment by acn-tsumura** [comment]
６．PR作成完了として検収担当者に依頼

**Comment by acn-tsumura** [comment]
リリースタグを設定しました。
https://github.com/matsuo-y/git-practice-lunch/releases/tag/v4.3

**Comment by acn-tsumura** [comment]
@opst-oshima デプロイを確認できました。クローズをお願い致します。

![issue61_1](https://cloud.githubusercontent.com/assets/12555037/24856620/58e63c26-1e20-11e7-9ff6-4435ec807a05.png)

**Comment by opst-oshima** [comment]
確認しました。issueをcloseします。
