### ISSUE TITLE
2017.05.01-2017.05.02 breakfast

### ISSUE THREAD

**Issue by ghost** [matsuo-y/git-practice#65]
## 作業内容
5/1、5/2のの朝ごはんを以下のサイトで公開できる

branch作成以降の実際の開発タスクについては、[matsuo-y/git-practice-breakfast](https://github.com/matsuo-y/git-practice-breakfast)リポジトリで行う
※matsuo-y/git-practice-breakfastリポジトリにはissueは作成せず、PRは直接このissueにconnectさせること

origin/git-practice/#{N}-breakfastで作業を行い、origin/stagingにPRしてマージする
また、開発担当者はorigin/git-practice/#{N}-{name}-breakfast-{mmdd}というブランチを作成して作業を実施する
コミットメッセージは、誰の朝食か（どんな修正か）がわかる文言にする
PRのタイトルは、誰の朝食かがわかる文言にする

## 開発時に使用する環境
環境 | URL
--- | ---
PR環境 | https://git-practice-breakfast-pr-{N}.herokuapp.com/
ステージング環境 | https://staging-git-practice-breakfast.herokuapp.com/breakfast/201705.html
本番環境 | https://matsuo-y.github.io/git-practice-breakfast/breakfast/201705.html

  PR時にはPR番号{N}の環境をブラウザで確認する

## 作業担当者の割り当て
- issue作成者：江嵜
- branch作成者：彌永
- 開発担当者(朝食報告、4名)：彌永、江嵜、郷野、根本
- 検収担当者：江嵜
- リリース担当者：彌永

## 判定基準
- [x] issue作成者が、issueを作成した
- [x] branch作成者が、issue branchを作成した
- [x] 開発担当者が、origin/git-practice/#{N}-breakfastへのPRを作成した
PRのアサインは、彌永→江嵜→郷野→根本→彌永の順にする
- [x] 開発担当者が、回ってきたorigin/git-practice/#{N}-breakfastへのPRをマージ完了した
- [x] リリース担当者が、staging branchへのPRを作成した
- [x] 検収担当者が、staging branchへのPRをマージ完了した
- [x] リリース担当者が、master branchへのPRを作成した
- [x] 検収担当者が、master branchへのPRをマージ完了した
- [x] リリース担当者が、master branchのHEADに対して、releases/tagsを設定し、issueに記載した
- [x] リリース担当者が、master branch がデプロイされた結果を確認し、issueに確認した結果を記載した
- [x] 検収担当者が、issueをcloseした

**Comment by iyanagaopst** [comment]
リリースタグの設定を行いました。
https://github.com/matsuo-y/git-practice-breakfast/releases/tag/v1.6

**Comment by iyanagaopst** [comment]
![image](https://cloud.githubusercontent.com/assets/27798777/25603026/6d0788da-2f33-11e7-9104-8f0c49456621.png)

**Comment by iyanagaopst** [comment]
@opst-ezaki 
issueのcloseをお願い致します。

**Comment by ghost** [comment]
@iyanagaopst 
確認いたしました。
close いたします。
