### ISSUE TITLE
2016.10.26 lunch

### ISSUE THREAD

**Issue by opst-fujimoto** [matsuo-y/git-practice#7]
昼食は、10/26だけの開発期間を想定した練習

今日の昼ごはんを以下のサイトで公開できる

ステージング環境： https://staging-git-practice-lunch.herokuapp.com/lunch/201610.html
本番環境：　https://matsuo-y.github.io/git-practice-lunch/lunch/201610.html

担当者は以下のとおり(作業内容はREADME.mdに記載)
# 昼食
- issue作成者：譚
- branch作成者：松尾
- PR担当者(昼食報告担当)：中村
- リリース担当者：上田

**Comment by matsuo-y** [comment]
masterへのマージが終わったためクローズします。
