### ISSUE TITLE
2017.06.06-2017.06.07 breakfast

### ISSUE THREAD

**Issue by ghost** [matsuo-y/git-practice#70]
## 作業内容
06/06、06/07のの朝ごはんを以下のサイトで公開できる

branch作成以降の実際の開発タスクについては、[matsuo-y/git-practice-breakfast](https://github.com/matsuo-y/git-practice-breakfast)リポジトリで行う

※
- matsuo-y/git-practice-breakfastリポジトリにはissueを作成しない
- matsuo-y/git-practice-breakfastリポジトリ内に作成したPRは、matsuo-y/git-practiceリポジトリのissueにconnectさせる

### 作業フロー

1. branch 作成者は `origin/master` ブランチから `origin/git-practice/#{N}-breakfast` ブランチを作成する

1. 各開発担当者は `origin/git-practice/#{N}-breakfast` から `git-practice/#{N}-{name}-breakfast-{mmdd}` というブランチを作成しローカルにて作業を実施する

1. ローカルにて作業をコミットする  
  コミットメッセージは、 `matsuo-y/git-practice#{N} 誰の朝食か（どんな修正か）` の形式にする

1. コミットをリモートへプッシュし、PR を作成する  
  PRのタイトルは、`git-practice/#{N}-{name}-breakfast-{mmdd}からgit-practice/#{N}-breakfastへのマージ(git-practice/#{N})` とする

1. PR をレビュアーへ回し、レビューしてもらう
  レビュアーのアサインは  
  遠藤→江嵜→根本→松尾→遠藤 にお願いするものとする

1. PR のレビュアーは編集内容を確認し、間違いやコンフリクト発生などの問題がなければマージする。  
  また、マージした作業ブランチ( `git-practice/#{N}-{name}-breakfast-{mmdd}` )の削除を行う。
  問題がある場合は、編集者へその内容を報告し、修正してもらう。

1. 全ての内容が `origin/git-practice/#{N}-breakfast` へマージされた時点で、リリース担当者は `origin/master` ブランチへの PR を作成する。  
  PR タイトルは `git-practice/#{N}-breakfastからmasterへのマージ(git-practice/#{N})` とする。

1. 検収担当者は内容を確認後、問題がなければマージする。
  また、マージした作業ブランチ( `git-practice/#{N}-breakfast` )の削除を行う。

1. リリース担当者はリリースタグの設定・リリース結果確認を行う。

1. 検収担当者はリリース担当者の記録を確認し、 issue をクローズする。

## 開発時に使用する環境
環境 | URL
--- | ---
PR環境 | https://git-practice-breakfast-pr-{N}.herokuapp.com/
本番環境 | https://matsuo-y.github.io/git-practice-breakfast/breakfast/201705.html

  PR時にはPR番号{N}の環境をブラウザで確認する

## 作業担当者の割り当て
- issue作成者：江嵜
- branch作成者：遠藤
- 開発担当者(朝食報告、4名)：遠藤、江嵜、根本、松尾
- 検収担当者：江嵜
- リリース担当者：遠藤

## 判定基準
- [x] issue作成者が、issueを作成した
- [x] branch作成者が、issue branchを作成した
- [ ] 開発担当者が、`git-practice/#{N}-breakfast` ブランチへのPRを作成した
- [ ] 開発担当者が、回ってきた `git-practice/#{N}-breakfast` ブランチへのPRをマージ完了した
- [ ] リリース担当者が、master branchへのPRを作成した
- [ ] 検収担当者が、master branchへのPRをマージ完了した
- [ ] リリース担当者が、master branchのHEADに対して、releases/tagsを設定し、issueに記載した
- [ ] リリース担当者が、master branch がデプロイされた結果を確認し、issueに確認した結果を記載した
- [ ] 検収担当者が、issueをcloseした

**Comment by opstendo** [comment]
リリースタグの設定を行いました

https://github.com/matsuo-y/git-practice-breakfast/releases/tag/v1.7

**Comment by opstendo** [comment]
本番環境へデプロイされたことを確認いたしました。

![image](https://user-images.githubusercontent.com/29187912/26869870-fca7e822-4ba8-11e7-8197-af84e04d94c7.png)

![image](https://user-images.githubusercontent.com/29187912/26869882-0814aa38-4ba9-11e7-9050-87492dc69fc6.png)

**Comment by ghost** [comment]
リリースを確認致しました。クローズいたします。
