### ISSUE TITLE
2018.04.04-2018.04.05 breakfast

### ISSUE THREAD

**Issue by gonomk** [matsuo-y/git-practice#76]
## 作業内容
4/4、4/5の朝ごはんを以下のサイトで公開できる

branch作成以降の実際の開発タスクについては、[matsuo-y/git-practice-breakfast](https://github.com/matsuo-y/git-practice-breakfast)リポジトリで行う

- matsuo-y/git-practice-breakfastリポジトリにはissueを作成しない
- matsuo-y/git-practice-breakfastリポジトリ内に作成したPRは、matsuo-y/git-practiceリポジトリのissueにconnectさせる

## 作業フロー

1. branch 作成者は origin/master ブランチから origin/git-practice/#{N}-breakfast ブランチを作成する

2. 各開発担当者は origin/git-practice/#{N}-breakfast から git-practice/#{N}-{name}-breakfast-{mmdd} というブランチを作成しローカルにて作業を実施する

3. ローカルにて作業をコミットする  
コミットメッセージは、 matsuo-y/git-practice#{N} 誰の朝食か（どんな修正か） の形式にする

4. コミットをリモートへプッシュし、PR を作成する  
PRのタイトルは、git-practice/#{N}-{name}-breakfast-{mmdd}からgit-practice/#{N}-breakfastへのマージ(git-practice/#{N}) とする

5. PR をレビュアーへ回し、レビューしてもらう  
レビュアーのアサインは  
山崎→郷野→根本→山崎 にお願いするものとする

6. PR のレビュアーは編集内容を確認し、間違いやコンフリクト発生などの問題がなければマージする。  
また、マージした作業ブランチ( git-practice/#{N}-{name}-breakfast-{mmdd} )の削除を行う。
問題がある場合は、編集者へその内容を報告し、修正してもらう。

7. 全ての内容が origin/git-practice/#{N}-breakfast へマージされた時点で、リリース担当者は origin/master ブランチへの PR を作成する。  
PR タイトルは git-practice/#{N}-breakfastからmasterへのマージ(git-practice/#{N}) とする。

8. 検収担当者は内容を確認後、問題がなければマージする。  
また、マージした作業ブランチ( git-practice/#{N}-breakfast )の削除を行う。

9. リリース担当者はリリースタグの設定・リリース結果確認を行う。

10. 検収担当者はリリース担当者の記録を確認し、 issue をクローズする。

## 開発時に使用する環境
環境 | URL
--- | ---
PR環境 | https://git-practice-breakfast-pr-{N}.herokuapp.com/
本番環境 | https://matsuo-y.github.io/git-practice-breakfast/breakfast/201804.html

  PR時にはPR番号{N}の環境をブラウザで確認する

## 作業担当者の割り当て
- issue作成者：郷野
- branch作成者：山崎
- 開発担当者(朝食報告、3名)：山崎、郷野、根本
- 検収担当者：根本
- リリース担当者：山崎

## 判定基準
- [x] issue作成者が、issueを作成した
- [x] branch作成者が、issue branchを作成した
- [x] 開発担当者が、git-practice/#{N}-breakfast ブランチへのPRを作成した
- [x] 開発担当者が、回ってきた git-practice/#{N}-breakfast ブランチへのPRをマージ完了した
- [x] リリース担当者が、master branchへのPRを作成した
- [x] 検収担当者が、master branchへのPRをマージ完了した
- [x] リリース担当者が、master branchのHEADに対して、releases/tagsを設定し、issueに記載した
- [x] リリース担当者が、master branch がデプロイされた結果を確認し、issueに確認した結果を記載した
 検収担当者が、issueをcloseした

**Comment by yamazakiopst** [comment]
タグの設定を行いました。
https://github.com/matsuo-y/git-practice-breakfast/releases/tag/v1.8

**Comment by yamazakiopst** [comment]
本番環境の確認完了です。
![honnbann](https://user-images.githubusercontent.com/37561977/38349520-71958550-38e2-11e8-9b53-502c99433667.png)

**Comment by yamazakiopst** [comment]
@opst-nemoto close確認お願いします

**Comment by opst-nemoto** [comment]
@yamazakiopst リリース完了が確認できたのでクローズします。
