### ISSUE TITLE
2018.04.12-2018.04.17 breakfast

### ISSUE THREAD

**Issue by yamazakiopst** [matsuo-y/git-practice#80]
## 作業内容
4/12-4/17の朝ごはんを以下のサイトで公開できる

branch作成以降の実際の開発タスクについては、[matsuo-y/git-practice-breakfast](https://github.com/matsuo-y/git-practice-breakfast)リポジトリで行う

- matsuo-y/git-practice-breakfastリポジトリにはissueを作成しない
- matsuo-y/git-practice-breakfastリポジトリ内に作成したPRは、matsuo-y/git-practiceリポジトリのissueにconnectさせる

## 作業フロー

1. branch 作成者はローカルリポジトリの master ブランチをチェックアウトする
リモートリポジトリの master ブランチをプルして、ローカルリポジトリの master ブランチへリモートリポジトリの master ブランチの最新コミットの取得と反映を行う
ローカルリポジトリの master ブランチからgit-practice/#{N}-breakfast ブランチを作成しプッシュする

2. 各開発担当者は ローカルリポジトリの git-practice/#{N}-breakfast ブランチをチェックアウトし、リモートリポジトリの git-practice/#{N}-breakfast をプルして git-practice/#{N}-{name}-breakfast-{mmdd} ブランチをローカルリポジトリに作成する
ローカルリポジトリにて作業を実施する

3. ローカルリポジトリにて作業をコミットする  
コミットメッセージは、 matsuo-y/git-practice#{N} 誰の朝食か（どんな修正か） の形式にする

4. コミットをリモートリポジトリへプッシュし、PR を作成する  
PRのタイトルは、git-practice/#{N}-{name}-breakfast-{mmdd}からgit-practice/#{N}-breakfastへのマージ(git-practice/#{N}) とする

5. PR をレビュアーへ回し、レビューしてもらう  
レビュアーのアサインは  
町田→山崎→坂部→町田 にお願いするものとする

6. PR のレビュアーは編集内容を確認し、間違いやコンフリクト発生などの問題がなければマージする。  
また、マージした作業ブランチ( git-practice/#{N}-{name}-breakfast-{mmdd} )の削除を行う。
問題がある場合は、編集者へその内容を報告し、修正してもらう。

7. 全ての内容が リモートリポジトリの git-practice/#{N}-breakfast へマージされた時点で、リリース担当者は リモートリポジトリの master ブランチへの PR を作成する。  
PR タイトルは git-practice/#{N}-breakfastからmasterへのマージ(git-practice/#{N}) とする。

8. 検収担当者は内容を確認後、問題がなければマージする。  
また、マージした作業ブランチ( git-practice/#{N}-breakfast )の削除を行う。

9. リリース担当者はリリースタグの設定・リリース結果確認を行う。

10. 検収担当者はリリース担当者の記録を確認し、 issue をクローズする。

## 開発時に使用する環境
環境 | URL
--- | ---
PR環境 | https://git-practice-breakfast-pr-{N}.herokuapp.com/
本番環境 | https://matsuo-y.github.io/git-practice-breakfast/breakfast/201804.html

  PR時にはPR番号{N}の環境をブラウザで確認する

## 作業担当者の割り当て
- issue作成者：山崎
- branch作成者：坂部
- 開発担当者(朝食報告、3名)：山崎、坂部、町田
- 検収担当者：山崎
- リリース担当者：町田

## 判定基準
- [x] issue作成者が、issueを作成した
- [x] branch作成者が、issue branchを作成した
- [x] 開発担当者が、git-practice/#{N}-breakfast ブランチへのPRを作成した
- [x] 開発担当者が、回ってきた git-practice/#{N}-breakfast ブランチへのPRをマージ完了した
- [x] リリース担当者が、master branchへのPRを作成した
- [x] 検収担当者が、master branchへのPRをマージ完了した
- [x] リリース担当者が、master branchのHEADに対して、releases/tagsを設定し、issueに記載した
- [x] リリース担当者が、master branch がデプロイされた結果を確認し、issueに確認した結果を記載した
 検収担当者が、issueをcloseした

**Comment by ebook-sakabe** [comment]
@yamazakiopst PRマージしました。

**Comment by ebook-gono** [comment]
![image](https://user-images.githubusercontent.com/35320452/38842852-45f6dd9c-4227-11e8-8110-cc8cdd267e05.png)

**Comment by opst-machida** [comment]
タグ付け
https://github.com/matsuo-y/git-practice-breakfast/releases/tag/v1.9

**Comment by opst-machida** [comment]
リリース結果
![image](https://user-images.githubusercontent.com/38242513/38966539-badede42-43bd-11e8-8958-5453517d08af.png)

**Comment by opst-machida** [comment]
@yamazakiopst リリースが完了しました。確認をお願いいたします。

**Comment by yamazakiopst** [comment]
@opst-machida 確認しましたのでクローズします
